config/routes.rb
Rails.application.routes.draw do
  root to: 'tops#index'
  resources :users, only: %i[new destroy]
  resources :wastings, only: %i[create show edit update destroy]
  resources :terms_of_services, only: %i[index]
  resources :privacy_policys, only: %i[index]
  resource  :my_page, only: %i[show]
end

app/views/shared/_before_login_header.html.slim
header.page-header.wrapper
  .nav.navbar.fixed-top.navbar-expand-md.bg-dark.navbar-dark
    .navbar-brand
      h3
        = link_to root_path, id: 'header-logo' do 
          | NO無駄遣い(仮)

app/views/shared/_error_messages.html.slim
- if model.errors.any?
  .alert.alert-danger
    ul
      - model.errors.full_messages.each do |message|
        li= message

app/views/shared/_flash.html.slim
- if flash.notice
  .alert.alert-success.alert-dismissible.fade.show
    = flash.notice
- if flash.alert
  .alert.alert-danger.alert-dismissible.fade.show
    = flash.alert

app/views/shared/_footer.html.slim
footer.text-center.fixed-bottom.bg-dark.navbar-dark id= 'footer'
  small Copyright © 2021. NO無駄遣い(仮)
  ul.footer-menu
    li= link_to '利用規約', terms_of_services_path, style: 'color: white;'
    li= link_to 'プライバシーポリシー', privacy_policys_path, style: 'color: white;'

app/views/shared/_header.html.slim
header.page-header.wrapper
  .nav.navbar.fixed-top.navbar-expand-md.text-dark
    / .navbar-brand
    /   h3
    /     = link_to root_path, id: 'header-logo' do 
    /       = image_tag 'logo.png', size: '100x70'

    / .collapse.navbar-collapse id='navbarSupportedContent'
    /   ul.navbar-nav.ml-auto.main-nav.align-items-center id='header-links'
    /     i.nav-item= link_to 'ログアウト', user_path(@current_user), method: :delete, class: 'nav-link'